### ISSUE TITLE
Working with select dropdowns

### ISSUE THREAD

**Issue by carolineorlando** [chrisguitarguy/Front-End-Accounts#10]
Is there a special way to work with select dropdowns?

For example, the default "display name" field is by default a dropdown, but it's been converted to a text input field below:

       // XXX this is a select in the admin area, not going to do that here...
       $this->form->addField('display_name', array(
            'label'         => __('Display Name', FE_ACCOUNTS_TD),
       ));

Is there a way to convert it back to a select? (This, and other custom profile meta fields that are displayed as selects)

**Comment by chrisguitarguy** [comment]
You can use the `type` argument to the field.

```php
$this->form->addField('display_name', array(
  'label' => __('Display Name', 'your_text_domain'),
  'type' => 'select',
  'choices' => generate_display_name_choices_somehow(),
));
```

The `generate_display_name_choices_somehow` bit was why I didn't do it as a select box: didn't want to figure out how to do that on the frontend in the same was as in the admin area.

You can hook in and modify the account for to suit your needs:

```php
add_action('frontend_accounts_alter_account_form', function ($form, $user) {
  $this->form->addField('display_name', array(
    'label' => __('Display Name', 'your_text_domain'),
    'type' => 'select',
    'choices' => generate_display_name_choices_somehow($user),
  ));
}, 10, 2);
```

Calling `addField` with an already existing field will replace it.

**Comment by carolineorlando** [comment]
Beautiful!

**Comment by chrisguitarguy** [comment]
Choices should be an associative array, so the key values (what will be stored) can be whatever you need them to be:

```
function generate_school_name_choices($user)
{
    $terms = get_terms('school', 'hide_empty=0'); 
    foreach ($terms as $term) { 
        $choices[$term->slug] = $term->name;
        // OR something complicated like
        $choices["{$term->slug}-{$term->term_id}"] = $term->name;
    } 

    return $choices;
}
```

**Comment by carolineorlando** [comment]
Just as I was reading through /Field/select.php ...

Thank you!
