### ISSUE TITLE
Textarea value not printing

### ISSUE THREAD

**Issue by carolineorlando** [chrisguitarguy/Front-End-Accounts#11]
Textarea form fields are not printing values to the front-end field. I think it's something with this (in particular, line 30):

[Form/Field/Textarea.php, Lines 25-30] (https://github.com/chrisguitarguy/Front-End-Accounts/blob/master/inc/Form/Field/Textarea.php#L25-L30)

The values are saving properly (for example, the back-end profile.php description field stores and prints the description value properly), but it does not display in the front-end form field. (The same issue is occurring with select fields.)

**Comment by chrisguitarguy** [comment]
So it turns out the code here wasn't actually saving the user description on the front end. It would appear to work sometimes because the value of the field was bound to whatever was submitted, but then a reload of the page would make it disappear.

That's fixed now!

As far as...

> The same issue is occurring with select fields.

I would suspect, it's the same? If you've added select fields to a form, did you [hook in and save it](https://github.com/chrisguitarguy/Front-End-Accounts#modifying-sections)?

**Comment by carolineorlando** [comment]
Thanks, Chris! That was it (for the description field) - but it appears as though hooking + saving new fields doesn't save on the front-end either.

```
use Chrisguitarguy\FrontEndAccounts\Form;

add_action('frontend_accounts_alter_account_form', function($form) {
    $form->addField('phone', array(
        'label'          => 'Phone Number', 
        'type'          => 'text',
        'validators'    => array(
            new Form\Validator\NotEmpty(__( 'Please enter a phone number', 'text-domain' )),
        ),
        'required'      => true, // HTML5, client side validation
    ));
	
    $form->addField('school_slug', array(
        'label'          => 'School', 
        'type' => 'select',
	'choices' => generate_school_name_choices(),
        'validators'    => array(
            new Form\Validator\NotEmpty(__( 'Please select your school', 'text-domain' )),
        ),
        'required'      => true, // HTML5, client side validation
    ));	
});

add_action(
    'frontend_accounts_account_post_save_user',
    function( $user, $formdata, $account_obj ) {

        // save phone data
        if ( isset( $formdata['phone'] ) ) {
            update_user_meta( $user->ID, 'phone', $formdata['phone'] );
        } else {
            $account_obj->addError('no_phone', __( 'Please provide a phone number.', 'text-domain') );
        }
		
        // save school data
        if ( isset( $formdata['school_slug'] ) ) {
            update_user_meta( $user->ID, 'school_slug', $formdata['school_slug'] );
			
			$term = get_term_by( 'slug', $formdata['school_slug'], 'school' ); 
			$name = $term->name;
	                update_user_meta( $user->ID, 'school_name', $name );

        } else {
            $account_obj->addError( 'no_school', __( 'Please select a school.', 'text-domain' ) );
        }	
    },
    10,
    4
);
```

**Comment by chrisguitarguy** [comment]
Okay, I think the data is getting saved, but the frontend doesn't get populated with the value. You can set an initial value like this for the account form:

```php
add_filter('frontend_accounts_account_form_initial', function ($vals, $user) {
  $vals['phone'] = get_user_meta($user->ID, 'phone', true);
  return $vals;
}, 10, 2);
```

As of a few minutes ago, you can also do something like this:

```php
add_action('frontend_accounts_alter_account_form', function ($form, $user) {
  $field = $form->addField('phone', [
    'label' => __('Phone', 'your_textdomain'),
    // ...
  ]);
  $field->setValue(get_user_meta($user->ID, 'phone', true));
});
```

**Comment by carolineorlando** [comment]
Hey Chris,

Tried both of these methods, neither work. I'm not sure that the data is being saved...

**Comment by chrisguitarguy** [comment]
You have to write the code to save custom fields. Check out this bit of the readme: https://github.com/chrisguitarguy/Front-End-Accounts#modifying-sections

Here's the code:

```php
add_action(
    'frontend_accounts_account_post_save_user',
    function($user, $formdata, $account_obj) {
        // this fires AFTER wp_update_user tries to save the user

        // $user is the WP_User object

        // $formdata is the validated data from the form

        // $account_obj is the that called do_action, it provides some
        // helpful methods: addError and removeError for showing errors
        // to users.

        // remember the validator above? phone_number should always be set.
        if (isset($formdata['phone_number'])) {
            update_user_meta($user->ID, 'yourprefix_phone_number', $formdata['phone_number']);
        } else {
            // show an error!
            $account_obj->addError('no_phone', __('Please provide a phone number.', 'your_textdomain'));
        }
    },
    10,
    4
);
```

**Comment by carolineorlando** [comment]
Ok, so this was in my files properly (your documentation is very good :+1:) but there seems to be a conflict with this plugin and updating/saving custom field values within the WordPress native profile.php (backend profile). 

Anyway, after removing the custom fields functions that were hooking into show_user_profile, edit_user_profile, edit_user_profile_update, and personal_options_update functions - everything works/saves as is.
