### ISSUE TITLE
/account/login does not render form

### ISSUE THREAD

**Issue by carolineorlando** [chrisguitarguy/Front-End-Accounts#12]
/account/login does not work (the form does not render)...

**Comment by chrisguitarguy** [comment]
Couple questions:

1. Does `/account/login/`(with the trailing slash) work?
2. Go to Settings -> Permalinks and hit save. Does the form work after that?

**Comment by carolineorlando** [comment]
Update (after taking a look at error logs...)

Call to undefined method Chrisguitarguy\FrontEndAccounts\Form\Field\TextInput::addField() in /nas/wp/www/XXXXXXXX/wp-content/plugins/Front-End-Accounts-master/inc/Login.php on line 127

**Comment by chrisguitarguy** [comment]
Should be fixed in master now, sorry about that. Changed the behavior of forms in 2b45683163342499adf638a956d42b599aefa742 and didn't catch all the uses.
