### ISSUE TITLE
password clears on /account/edit save if left blank

### ISSUE THREAD

**Issue by carolineorlando** [chrisguitarguy/Front-End-Accounts#13]
the user password clears if the two password input fields are left blank on account save

**Comment by chrisguitarguy** [comment]
What do you mean by clears?

If you mean that the password fields are blank, then that's intention. WordPress doesn't store a plaintext password to put in the value and generally you don't expose sensitive information like that in a form field anyway.

Or do you mean the user password is changed?

**Comment by carolineorlando** [comment]
Sorry, I should have been more descriptive: the user password is changed

**Comment by carolineorlando** [comment]
From what's going on in the DB, save with blank password input fields sets the password to a completely different value (hash in wp_users table changes), so the user is forced to reset if if he/she signs out.

**Comment by chrisguitarguy** [comment]
Thanks, I'll take a look tonight

**Comment by carolineorlando** [comment]
Sure, I'm digging into Accounts.php now. will let you know if I see anything funky

**Comment by chrisguitarguy** [comment]
Here's the [password change stuff](https://github.com/chrisguitarguy/Front-End-Accounts/blob/d4b6f41c687865aa84ad88cc7438b2ed573121a3/inc/Account.php#L201). Pull requests are always welcome if you find a fix :+1:

**Comment by nlemoine** [comment]
Another bug left on edit profile.

**Comment by chrisguitarguy** [comment]
Fixed in 8d4bdbe7872b495e920121e0f71d9562b8e0879d
