### ISSUE TITLE
Input "file" type?

### ISSUE THREAD

**Issue by carolineorlando** [chrisguitarguy/Front-End-Accounts#9]
Hey Chris,

Can "file" input types be added on to the /account/edit page? (Ideally, account/register, too)

        $this->form->addField('avatar', array(
            'label'         => __('Photo', FE_ACCOUNTS_TD),
            'type'          => 'file',
        ));

I tried the above, but received a "invalid field" error :(

Let me know, thanks.

**Comment by chrisguitarguy** [comment]
It's not currently supported, no. You could [add](https://github.com/chrisguitarguy/Front-End-Accounts/blob/33d04b93cc8bf4ed6d6ff8bb236b958b68fb798c/inc/Form/Form.php#L155) [it](https://github.com/chrisguitarguy/Front-End-Accounts/tree/master/inc/Form/Field) via a pull request if you like.

**Comment by carolineorlando** [comment]
OK, thanks Chris.

**Comment by chrisguitarguy** [comment]
@carolineorlando I just added a filter to allow hooking in and using custom field types.

See 2063769a4b59e37fd9c1a9726febe0b672f9e53c there's a small sample there. The custom field object just need to implement `Chrisguitarguy\FrontEndAccounts\Form\Field\FieldInterface`

**Comment by chrisguitarguy** [comment]
I've added a `file` type to the core:


```php
$form->addField('some_file', [
  'type' => 'file',
  // ...
]);
```
